### ISSUE TITLE
How to close the sliding event

### ISSUE THREAD

**Issue by xlievo** [TrekDev/Xamarin.Android.ResideMenu#1]
How to close the sliding event ?
How override bool DispatchTouchEvent ?

Thank you !

**Comment by jeremy-ellis-tech** [comment]
Hi xlievo,

I'm sorry, but I don't quite understand the questions. Can you be more specific?

-TrekDev

**Comment by xlievo** [comment]
How to disable the left and right sliding  to open the menu?
Sorry for my language problem.

**Comment by jeremy-ellis-tech** [comment]
Hi xlievo, ~~I don't think you can do that as it is, but shouldn't be difficult to add.~~

EDIT: You can disable both left and right swipe directions, see my next comment.

**Comment by xlievo** [comment]
I think so, in fact, I want to know why this bool attribute is not built on the source
There is no way to work in the presentation. Please check.

ResideMenu.Demo\MenuActivity.cs

public override bool DispatchTouchEvent(MotionEvent ev)
{
      //return ResideMenu.DispatchTouchEvent(ev);
      return base.DispatchTouchEvent(ev);
}

**Comment by jeremy-ellis-tech** [comment]
Hi xlievo,

[That line looks correct, from what I have translated.](https://github.com/SpecialCyCi/AndroidResideMenu/blob/master/ResideMenuDemo/src/com/special/ResideMenuDemo/MenuActivity.java#L81)

Also, I have just had a closer look, and you can disable swipe directions via `ResideMenu.SetSwipeDirectionDisable(Direction.Left)` and `ResideMenu.SetSwipeDirectionDisable(Direction.Right)`.

If you disable both left and right, it should disable the menu. I missed it as it's been a while since I've worked on this project.

Is that what you wanted?

-TrekDev

**Comment by xlievo** [comment]
ResideMenu.SetSwipeDirectionDisable OK!

Thank you. This is what I want.
Great experience
Thank you for your help.

**Comment by jeremy-ellis-tech** [comment]
No problem

If you have any other problems feel free to open another issue.
- TrekDev
